# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_console', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedemail',
            name='email_prefix',
        ),
        migrations.AddField(
            model_name='generatedemail',
            name='email',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
