# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_console', '0003_auto_20170401_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedemail',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
