# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 16:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_console', '0005_auto_20170523_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedemail',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='generatedemail',
            name='hidden',
        ),
        migrations.AddField(
            model_name='generatedemail',
            name='visibility',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
