# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 18:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('forward', models.BooleanField(default=True)),
                ('visibility', models.CharField(choices=[('VISIBLE', 'Email is visible on the dashboard.'), ('HIDDEN', 'Email is removed, but can be readded.'), ('DELETED', 'Email is permanently deleted.')], default='VISIBLE', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
